clip_preprocessor:
  class: preprocessor.clip_preprocessor.CLIPPreprocessor
  args:
    image_size: 224  

masked_preprocessor:
  class: preprocessor.clip_preprocessor.MaskedPreprocessor
  args:
    image_size: 224
    patch_size: 16
    mask_ratio: 0.5

patch_cut_preprocessor_random:
  class: preprocessor.clip_preprocessor.PatchCutPreprocessor
  args:
    image_size: 224
    patch_selection: 'random'

patch_cut_preprocessor_external:
  class: preprocessor.clip_preprocessor.PatchCutPreprocessor
  args:
    image_size: 224
    patch_selection: 'external'

gpt_caption_preprocessor:
  class: preprocessor.clip_preprocessor.GPTCaptionPreprocessor
  args:
    prompt: "You are a helpful assistant, please rewrite the following caption to be more descriptive and detailed: "
    model: 'gpt-4o-mini'
