# Default Config
default:
  gpu: [1,2,3]
  log_file: ckc_log.log


# Experiments Config
exp: 
  - class: evaluation
    dataset:
      class: coco_val_dataset
    args:
      sample_size: 5000
      metrics:
        - retrieval
        - uniformity
        - platonic:
            trials: 10
        - eigenfunction:
            save_path: ./eigenfunction_results

  # - class: contrastive_learning
  #   dataset:
  #     class: cc12m_train_dataset
  #     # class: coco_val_dataset
  #   args:
  #     epochs: 50
  #     batch_size: 1024
  #     max_iter: 100
  #     temperature_learnable: false
  
  - class: ckc_learning
    dataset:
      class: cc12m_train_dataset
      # class: coco_val_dataset
    args:
      infonce_weight: 0.1
      batch_size: 8192
      max_iter: 100
      update_iter: 100
      ckc_temperature: 0.07
  
  - class: evaluation
    dataset:
      class: coco_val_dataset
    args:
      sample_size: 5000
      metrics:
        - retrieval
        - uniformity
        - platonic:
            trials: 10
        - eigenfunction:
            save_path: ./eigenfunction_results

  # - class: contrastive_learning
  #   dataset:
  #     class: cc12m_train_dataset
  #     # class: coco_val_dataset
  #   args:
  #     epochs: 50
  #     batch_size: 1024
  #     max_iter: 300
  #     temperature_learnable: false

  - class: ckc_learning
    dataset:
      class: cc12m_train_dataset
      # class: coco_val_dataset
    args:
      infonce_weight: 0.1
      batch_size: 8192
      max_iter: 300
      update_iter: 300
      ckc_temperature: 0.07

  - class: evaluation
    dataset:
      class: coco_val_dataset
    args:
      sample_size: 5000
      metrics:
        - retrieval
        - uniformity
        - platonic:
            trials: 10
        - eigenfunction:
            save_path: ./eigenfunction_results

  # - class: contrastive_learning
  #   dataset:
  #     class: cc12m_train_dataset
  #     # class: coco_val_dataset
  #   args:
  #     epochs: 50
  #     batch_size: 1024
  #     max_iter: 500
  #     temperature_learnable: false
  
  - class: ckc_learning
    dataset:
      class: cc12m_train_dataset
      # class: coco_val_dataset
    args:
      infonce_weight: 0.1
      batch_size: 8192
      max_iter: 500
      update_iter: 500
      ckc_temperature: 0.07
  
  - class: evaluation
    dataset:
      class: coco_val_dataset
    args:
      sample_size: 5000
      metrics:
        - retrieval
        - uniformity
        - platonic:
            trials: 10
        - eigenfunction:
            save_path: ./eigenfunction_results

  # - class: contrastive_learning
  #   dataset:
  #     class: cc12m_train_dataset
  #     # class: coco_val_dataset
  #   args:
  #     epochs: 50
  #     batch_size: 1024
  #     max_iter: 1000
  #     temperature_learnable: false
  
  - class: ckc_learning
    dataset:
      class: cc12m_train_dataset
      # class: coco_val_dataset
    args:
      infonce_weight: 0.1
      batch_size: 8192
      max_iter: 1000
      update_iter: 1000
      ckc_temperature: 0.07
  

  - class: evaluation
    dataset:
      class: coco_val_dataset
    args:
      sample_size: 5000
      metrics:
        - retrieval
        - uniformity
        - platonic:
            trials: 10
        - eigenfunction:
            save_path: ./eigenfunction_results

  # - class: contrastive_learning
  #   dataset:
  #     class: cc12m_train_dataset
  #     # class: coco_val_dataset
  #   args:
  #     epochs: 50
  #     batch_size: 1024
  #     max_iter: 3000
  #     temperature_learnable: false
  
  - class: ckc_learning
    dataset:
      class: cc12m_train_dataset
      # class: coco_val_dataset
    args:
      infonce_weight: 0.1
      batch_size: 8192
      max_iter: 3000
      update_iter: 3000
      ckc_temperature: 0.07

  - class: evaluation
    dataset:
      class: coco_val_dataset
    args:
      sample_size: 5000
      metrics:
        - retrieval
        - uniformity
        - platonic:
            trials: 10
        - eigenfunction:
            save_path: ./eigenfunction_results


# Model Config
model:
  class: clip_vitb32

# Preprocessor Config
preprocessor:
  - class: image_preprocessor
    args:
      image_size: 224
  - class: text_preprocessor
    args:
      cutoff_length: 77
  - class: to_batch_preprocessor
    args: