# Default Config
default:
  gpu: 2
  log_file: clip_log.log


# Experiments Config
exp: 
  - class: ckc_learning
    dataset:
      # class: cc12m_train_dataset
      class: coco_val_dataset
    args:
      epochs: 10
      batch_size: 512
      update_iter: 20
      ckc_temperature: 0.01
  # - class: contrastive_learning
  #   dataset:
  #     # class: cc12m_train_dataset
  #     class: coco_val_dataset
  #   args:
  #     epochs: 50
  #     batch_size: 256
  #     temperature_learnable: false
  - class: retrieval
    dataset:
      class: coco_val_dataset
    args:
      sample_size: 5000
  - class: uniformity
    dataset:
      class: coco_val_dataset
    args:
      sample_size: 5000

# Model Config
model:
  class: clip_vitb32

# Preprocessor Config
preprocessor:
  - class: image_preprocessor
    args:
      image_size: 224
  # - class: gpt_caption_preprocessor
  #   args:
  #     model: gpt-3.5-turbo
  #     prompt: "You are a helpful assistant, please rewrite the following caption to be more descriptive and detailed: " 
  - class: text_preprocessor
    args:
      cutoff_length: 77
