default:
  exp: ContrastiveLearning
  
train:
  epochs: 100
  batch_size: 64
  lr: 1e-3
  scheduler: cosine

dataset:
  class: naive_dataset
  args:
    arg3: 10

model:
  class: clip_vitb32
  args:
    gpu: 0

preprocessor:
  - class: clip_preprocessor
    args:
      image_size: 224  